events {}

http {

    # Defines the path, memory zone name (10MB), and max disk size (10GB)
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;

    server {
        location / {
            proxy_cache my_cache;           # Uses the zone defined above
            proxy_pass http://host.docker.internal:9010;   # Origin server
            proxy_cache_valid 200 302 60m;  # Cache successful responses for 10 minutes
        }
    }
}