version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    network_mode: host

  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_DEBUG: "true"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_AUTH_API_URL: http://localhost:4000
    network_mode: host

  bionicpro-auth:
    build:
      context: ./task1/bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      KEYCLOAK_AUTH_SERVER_URL: http://localhost:8080/realms/reports-realm
      KEYCLOAK_CLIENT_ID: bionicpro-auth
      KEYCLOAK_CLIENT_SECRET: lPU9LFUfFfzBy2uh7MPJMuHSGzMp0VFM
      OAUTH2_CLIENT_REGISTRATION_LOGIN_SCOPE: openid
      OIDC_CALLBACK_URL: http://localhost:4000/callback
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - keycloak
    network_mode: host

  openldap:
    image: osixia/openldap:1.5.0
    command: --copy-service  --loglevel debug
    ports:
      - "389:389"
    environment:
      LDAP_DOMAIN: "example.com"
      OPENLDAP_BOOTSTRAP_ORGANIZATION: "example.com"
      OPENLDAP_BOOTSTRAP_SUFFIX: "dc=example,dc=com"
    volumes:
      - ./ldap/slapd-database:/var/lib/ldap
      - ./ldap/slapd-config:/etc/ldap/slapd.d
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/config.ldif
    network_mode: host
